### PR TITLE
Update to Python3

### PR DESCRIPTION
**Pull request by soulen3**
Hello, 

I've started work on moving Holland over to Python3. This breaks compatibility with Python2, so I've bumped the version number from 1.0.14 to 1.1.0.

Notes:
- Implemented fix for: https://github.com/holland-backup/holland/issues/185
  https://github.com/soulen3/holland/blob/python3/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py#L176
- Uses built in configobj instead of holland/core/config/configobj.py
- Only tested holland.backup.mysqldump/holland.lib.mysql/holland.lib.mysql plugins a this point

Thanks,
Steve

### CODE REVIEW

**Comment by soulen3** [comment]
Added configobj modules back, so Holland will still work on EL6 devices.

Tested on:
Ubuntu 18 with python 3.6
CentOS 7 python 2.7 & 3.4
CentOS 6 with python 2.6

Tested the following plugin:
mysqldump
mysql-lvm
mysqldump-lvm
xtrabackup

Thanks,
Steve

**Comment by soulen3** [comment]
@mikegriffin  Can you pleas take a look at my fix for https://github.com/holland-backup/holland/issues/185?

https://github.com/soulen3/holland/blob/python3/plugins/holland.backup.mysqldump/holland/backup/mysqldump/plugin.py#L176-L184

This change will also prevent Holland from skipping backups if "stop-slave" is enabled but "Slave_SQL_Running"  is no. I think this is better than throwing an error, and not creating a backup. Let me know if you can think of any problems with this.

Thanks,
Steve

**Comment by mikegriffin** [comment]
That is a double edged sword if you are relying on the slave for backups yet haven't deployed proper replication monitoring.

On the other hand, you might not be monitoring backup failures or replication could be temporarily stopped, as you might do while doing a schema change on the master, with the intent of promoting the slave for "rollback"

**Comment by soulen3** [comment]
I'll leave it as is then, so people will know what to expect.

Steve

**Comment by soulen3** [comment]
@mikegriffin @abg  Are there any changes or reviews you guys would like to do before I merge this?

Thanks,
Steve

**Pull request merged**
