### PR TITLE
Holland 1.2.2

### LINKED ISSUE #311: Mariabackup 10.4 causing issues
```Holland 1.1.21 started with pid 8688
--- Starting backup run ---
Creating backup path /backups/holland/mariabackup/20200813_101840
* Generating mysql option file: /backups/holland/mariabackup/20200813_101840/my.cnf
  + Added !include /root/.my.cnf
  + Added !include /etc/my.cnf
  + Added [client] section with credentials                             from [mysql:client] section
No backups purged
Estimated Backup Size: 225.18MB
Adjusting estimated size by 0.50 to 112.59MB
Starting backup[mariabackup/20200813_101840] via plugin mariabackup
Executing: /bin/mariabackup --version
/bin/mariabackup based on MariaDB server 10.4.14-MariaDB Linux (x86_64)
Executing: /bin/mariabackup --defaults-file=/backups/holland/mariabackup/20200813_101840/my.cnf --backup --stream=xbstream --tmpdir=/backups/holland/mariabackup/20200813_101840 --no-timestamp --target-dir=/backups/holland/mariabackup/20200813_101840
  > /backups/holland/mariabackup/20200813_101840/backup.mb.gz 2 > /backups/holland/mariabackup/20200813_101840/mariabackup.log
!! mariabackup  exited with failure status [2]
    ! /bin/mariabackup: unknown option '--no-timestamp'
mariabackup  exited with failure status [2]
Backup failed after 0.12 seconds
Purged failed backup: mariabackup/20200813_101840, failed-backup
Backup failed: Failed backup: mariabackup
Released lock /etc/holland/backupsets/mariabackup.conf
--- Ending backup run ---
```

` --no-timestamp`  is not supported by mariabackup 10.4   How can we remove that command line option, I am not including it anywhere.

### PR DESCRIPTION
**Pull request by soulen3**
- Fixes #311
- Get rid of tests that didn't work
- Search for mongodump using `which` function
- Fixes for travis-ci updates
- Update holland_commvault setup.py to use newer format

### CODE REVIEW

**Comment by acomputerwiz** [comment]
Any idea when this will get pushed to EPEL ?

**Comment by soulen3** [comment]
1.2.2 has been released for EL8, and fedora. At this point we're not planning on releasing any new packages for python2.  There's nothing preventing the EL8 version from working on older systems if you have the python3 dependencies met. 

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-a43e9eaaa5

**Comment by gregherrell** [comment]
Would it not be possible to at least get the mariabackup plugins under 2.7 pushed to EPEL? This is creating quite an issue for me as a Rackspace customer. We can no longer use Holland with Centos 7 and Mariabackup. 

This would at least provide a functioning option for many users of Holland.

**Comment by soulen3** [comment]
I've asked the package maintainers to create a holland3 package for EL7. They said they'll be able to get to it after the 1st of the year.  You'll still need to install python3, but those packages have been available in the base repos since EL 7.7.  

I've created an issue to track this.
https://github.com/holland-backup/holland/issues/317

**Pull request merged**
